### ISSUE TITLE
Build without Python dependency

### ISSUE THREAD

**Issue by saraedum** [conda-forge/cppyy-cling-feedstock#23]
Since cppyy-cling does not depend on Python we should be able to build only once for all Pythons.

**Comment by saraedum** [comment]
@isuruf: It used to be impossible to build an architecture specific Python package that actually does not depend on Python. Has this changed somehow? I mean, can we do a `ignore_run_exports` for Python or put python and pip into the build dependencies and `pip install --target`?

**Comment by isuruf** [comment]
This is still impossible at the moment.
